name: Test examples as a cron job

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+git://github.com/econ-ark/hark@master
      - name: Run examples
        run: |
          python examples/Gentle-Intro/Gentle-Intro-To-HARK.py
          python examples/Calibration/US_SSA_life_tables.py
          python examples/ConsIndShockModel/IndShockConsumerType.py
          python examples/ConsIndShockModel/KinkedRconsumerType.py
          python examples/ConsIndShockModel/PerfForesightConsumerType.py
          python examples/ConsumptionSaving/example_ConsMedModel.py
          python examples/ConsumptionSaving/example_TractableBufferStockModel.py
          python examples/ConsumptionSaving/example_ConsIndShock.py
          python examples/ConsumptionSaving/example_ConsPortfolioModel.py
          python examples/ConsumptionSaving/example_ConsLaborModel.py
          python examples/ConsumptionSaving/example_ConsMarkovModel.py
          python examples/ConsumptionSaving/example_ConsRepAgentModel.py
          python examples/ConsumptionSaving/example_ConsGenIncProcessModel.py
          python examples/ConsumptionSaving/example_ConsPrefShockModel.py
          python examples/ConsumptionSaving/example_ConsAggShockModel.py
          python examples/FashionVictim/FashionVictimModel.py
          python examples/GenIncProcessModel/GenIncProcessModel.py
          python examples/HowWeSolveIndShockConsumerType/HowWeSolveIndShockConsumerType.py
          python examples/LifecycleModel/LifecycleModel.py
    
