name: Test examples as a cron job

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: |
          python examples/Gentle-Intro/Gentle-Intro-To-HARK.py
    
