name: Test examples as a cron job

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install econ-ark==0.10.8
      - name: Run examples
        run: |
          python examples/Gentle-Intro/Gentle-Intro-To-HARK.py
    
